---
title: Welcome to our Lab Guide
---

Welcome to the lab guide for the Doss-Gollin lab in the Department of Civil and Environmental Engineering at Rice University.
If you're looking for our group's homepage, please find it [here](https://dossgollin-lab.github.io).

This document codifies lab practices and expectations for new and existing group members and is divided into three main sections:

1. **Lab Expectations** clarifies the expectations we have for ourselves and for one another.
1. **Lab How-To Guides** provides critical resources in the format of blog posts.
1. **Join Us** guides prospective group members through the process of joining.

::: {.callout-tip}
## Contribute
This is intended to be a **living document** and remains a work in progress.
Lab and community members are strongly encouraged to contribute to this document!
See [here](posts/contribute.qmd) for instructions.
:::

### Core values

1. **Creativity.**
    As academics, we enjoy the luxuries of freedom and space that allow us to question the status quo and explore new ideas.
    With this privilege comes a responsibility to imagine new possibilities and speak uncomfortable truths.
1. **Equity.**
    We recognize the burdens of systemic inequality and seek to promote fairness and justice.
1. **Excellence.**
    We strive for excellence in all our activities and aim to be role models in all that we do.
    We seek to do what is right, not what is easy, and acknowledge when we fall short.
1. **Humility.**
    We understand the limitations of our expertise and celebrate the academic and community partners with whom we coproduce knowledge.
    We overcome our limitations by actively seeking out diverse perspectives and challenging our preexisting assumptions.
1. **Open Science.**
    Our research is accessible to all levels of society.
    We approach complex problems with a collaborative mindset.
    When we make mistakes, we recognize them and do our best to fix them.

::: {.callout-note}
## Credit

The organization and framing of this document borrows heavily from lab guides written by
[Lab Carpentry](https://lab-carpentry.readthedocs.io/), 
the [Advanced Reactors and Fuel Cycles](http://arfc.npre.illinois.edu/manual/) group at UIUC,
the [Andersen Lab](andersenlab.org/dry-guide/) at Northwestern,
the [Computer-Oriented Geoscience Lab](https://www.compgeolab.org/manual/)  at University of Liverpool,
the [Ocean Transport Group](https://ocean-transport.github.io/) at the Lamont-Doherty Earth Observatory,
the [Aly lab](https://github.com/alylab/labmanual) at Columbia,
the [Srikrishnan Lab](https://viveks.bee.cornell.edu/lab-manual/) at Cornell,
and
the [Keller Lab Group](https://keller-lab.github.io/) at Dartmouth.
We thank Jordy Padilla and Yash Amonkar for constructive suggestions.
:::