---
title: "Responsibilities"
---

This page outlines the responsibilities of everyone in the group.
It is a living document and will be updated as the group evolves.
If you have any questions or concerns about these responsibilities, please reach out to James.

::: {.callout-tip}
## Caveat
Guidelines from Rice University, Rice Engineering, and Rice CEVE take precedence over this section.
If you believe that something on this page is at odds with university policy, please notify James.
:::

::: {.callout-tip}
## Credit
Specific language on this page comes from the [Ocean Transport Group](https://ocean-transport.github.io/) at the Lamont-Doherty Earth Observatory and the [MemoLab](https://github.com/memobc/memolab-manual) at Boston College.
:::

## Everyone

1. Be supportive of your labmates. We are a team.
1. Be physically present in the office on Thursdays and be generally reachable by Slack during normal working hours. We learn the most from one another.
1. Attend weekly group meetings as scheduled.
1. Do work that you are proud of. Do work that others will care about. If you feel as though your work does not meet these standards, speak up. Double-check your work. Being a little obsessive is essential to good science.
1. Share your knowledge. Exchanging knowledge and skills with your peers is the core of academic research.
1. If you have an issue with another lab member that cannot be solved by talking with them about it, please talk with James. If you have an issue with James, please reach out to another member of the department or the school of engineering.

## PI responsibilities

As the group leader, James has a unique and challenging range of responsibilities.

1. **Build an Inclusive Environment:** the PI is responsible for managing the social dynamic of the lab group to create a welcoming, inclusive, and productive environment.
1. **Define Research Directions for the Group:** Finding research questions that are socially relevant and scientifically novel is one of the hardest and most important components of basic applied research. It requires an awareness of the overall state of knowledge in the field, creativity, and plenty of luck.
1. **Define the Technical Approach:** Software and computing are very important to our group. The PI is working hard to provide a software and hardware environment that enables everyone else to be as productive as possible.
1. **Departmental Service:** The PI has lots of responsibilities to the department, including attending department meetings, participating in committees, and serving on student masters meetings / qualifying exams / thesis proposals / thesis defenses.
1. **Provide Scientific Mentoring:** It is the PI’s responsibility to help the junior members in the group develop into mature, independent scientists, capable of defining and executing their own research programs. Lab members will meet annually to sketch a strategic plan for the academic year and regularly (for now, weekly) to stay in touch.
1. **Manage the Publication Process:** Published papers are the main output of our team. The PI can help identify when results are ready to publish, select which journals to target, and help manage the ups and downs of the revision process.
1. **Obtain Funding:** Scientific research is expensive! A central role of the PI is to obtain grant funding to support our work, without which no research could happen.
1. **Professional Service:** The PI is expected to participate in professional organizations (e.g. AGU, AMS) and review papers and proposals on an ongoing basis.
1. **Provide Feedback:** The PI is expected to provide feedback on all aspects of research, including defining hypotheses and formulating questions; identifying specific methods and technical approaches; identifying relevant datasets; writing and debugging scientific code; producing figures and visualizations; managing data; and writing and editing papers. Feedback is also available on course selection, overall career goals, and long-term strategy.
1. **Provide Material Support:** You are never expected to spend any of your personal finances on anything related to research. All conference travel, computer supplies, books, etc. can be paid for with grant support (see item 2 above). Coordinate these expenses, in advance, with James.
1. **Provide Moral Support:** Graduate school, and research in general, can be an emotional roller coaster. James has been through these challenges personally and is always available to listen and provide advice (though you should also see the [Health Resources](./health.md) page).
1. **Provide Recommendation Letters:** You need them for almost every career move.
1. **Set Goals and Timelines:** The PI can help give structure to your project by defining specific milestones and timelines for their completion. Some people prefer to be closely managed in this way, while others may prefer a more hands-off approach.
1. **Sign Stuff:** There are lots of signatures needed to navigate the bureaucracy.
1. **Teach Classes:** The PI’s main job is to teach at least one course for semester, which occupies a large fraction of available time and effort.

## Grad Student Responsibilities

Graduate students are both students and workers, leading to a complex range of responsibilities to manage.

1. **Ask Questions!** If something is unclear to you -– either a science question or a procedural / administrative issue -– you should speak up.
1. **Develop Dissertation Research.** Ideally, your dissertation research will consist of at least 3 experiments that can be packaged into one thesis document.
1. **Apply for External Funding.** Applying to external funding (e.g., NSF GRFP) that you are eligible for is required of our graduate students, but even if it wasn’t, I would recommend it because it is such a valuable learning experience.
1. **Be Professional and Organized:** Develop a system that works for your for managing your responsibilities, coursework, and research. This is one of the biggest challenges of graduate school and there is no formula that works for everyone.
1. **Communicate** with the group and attend group meetings.
1. **Develop a Research Plan:** In consultation with your advisor, you should come up with a long-term plan for your research, with clearly defined milestones and goals. Each week, you should have a short term plan for exactly what to work on to move towards those goals.
1. **Develop Independence:** Your goal is to become an independent scientist. This means you should not hesitate to pursue your own ideas as they arise. Go to as many talks as you can to learn new things! Read (and re-read) papers in your field and outside it. Download that dataset and analyze it! Run that new model! Don’t wait to be told to do things. Take the initiative.
1. **Focus on your Research:** Your research is the most important part of your grad school experience. It should be your main priority, and you should approach it with the seriousness and professionalism you would a full-time job. It is easy to get caught up in coursework or TA-ing, but at the end of 5-ish years, you need to have completed a dissertation.
1. **Produce Reusable Data / Software:** In our group, we believe strongly that research is more than just papers. You are expected to share the outputs of your research (data and software) in a way that makes them reusable by the rest of the group and the rest of the field. See [Open Science](./open.md).
1. **Stay in Good Standing:** it is YOUR responsibility to understand all of the formal requirements of the graduate school and the department, and to stay ahead of all deadlines regarding registration, paperwork, qualifying exams, committee meetings, etc.
1. **Stay on Top of your Coursework:** The beginning of grad school is dominated by classes. You should strive to get as much as possible out of your coursework and connect it to your research wherever possible.
1. **Do Some Soul-Searching:** it is your responsibility to think about what type of career you want to pursue (e.g., academic jobs that are research-focused or teaching-focused, non-academic jobs like data science or science writing). We can brainstorm ways of making sure you are getting the training that you need and exposure to paths that you may be interested in.

## Undergraduate Responsibilities

Undergraduate students in the research group have a few core responsibilities.

1. Learn
1. Participate
1. Meet college requirements
1. Maintain average working rate of 10hrs/wk (unless otherwise discussed)
1. Track time spent working honestly and accurately
1. Plan for the future
1. Explore many paths
1. Submit weekly reports
1. Attend lab meetings when possible
1. Apply for scholarships, awards, and fellowships
1. Be helpful, friendly, and open to new ideas
