---
title: "Travel"
---

::: {.callout-note}
## Credit
Specific language on this page comes from the [MemoLab](https://github.com/memobc/memolab-manual) at Boston College.
:::

## Funding

The lab will typically pay for full-time lab members to present their work at major conferences (e.g., AGU, ASCE EWRI, etc.).
In general, the work should be "new" in that it has not been presented previously, and it should be appropriate for the conference.
Lab members should typically expect to travel to one major conference per year, subject to funding.

If you are interested in attending a conference, please discuss it with James well in advance!

### Travel budget

Grant budgets typically estimate flights plus $200 per day for hotel and meal costs, so your reimbursable costs should be around that amount or less.
If travel expenses are being paid off of a grant, additional restrictions may apply!

### Shared responsibility

Lab members are required to apply for other sources of funding available to them (e.g., departmental and university funds, conference student travel awards, etc.).

### Acommodations

Lab members may sometimes book shared accommodations (e.g, AirBnB) for travel.
This can save money and be more pleasant than staying at a hotel.
However, if you don't feel comfortable in a shared space you are welcome to arrange other accommodation.
Your individual safety and comfort in your lodging space should be of chief concern.

### Reimbursement

You typically have two choices for travel expenses: you can pay for expenses yourself and seek reimbursement through Rice, or you can ask James to pay for expenses directly using a Rice credit card.
In either case, you need to keep all receipts and organize them in a way that makes it easy to submit them for reimbursement.
Lab members are responsible for submitting their own expenses for reimbursement.

## Conduct

All expectations of conduct apply to members who are traveling.
Conferences and workshops may have further guidelines for conduct, and members are expected to follow both the letter and the spirit of these guidelines.

## Safety

Informal meetings and get-togethers, often at bars and restaurants, are an important component of many academic conferences and workshops.
These can be a fun and enjoyable way to develop long-lasting connections with colleagues at other institutions and to explore the cities where conferences are held.
Informal gatherings are also important for networking and can lead to future job offers and other opportunities.
Unfortunately, uncomfortable and unsafe situations can arise in these settings, particularly where the power dynamics of academia are mixed with relaxed settings and alcohol.
To care for ourselves and for one another, you should:

1. Have contact information (e.g., cell phone numbers) of other group members you are traveling with.
1. Let someone (another lab member or a friend who lab members could contact) know where you are.
1. Research the place you are visiting and have phone numbers handy that you can call if you need help.
1. Lab members who feel unsafe or think another lab member may be unsafe (including experiencing harassment) should seek help immediately. You should call James 24/7 if you suspect that a lab member *may* be unsafe.
