---
title: "Graduate Admissions"
---

If you are unsure whether you would be a good fit, you can send me an email of interest.
Please see below for instructions (if you send me a generic email I probably won't respond!)

## Open Positions

When funding is available for M.S. and Ph.D students to do specific work, these positions will be advertised on the group’s ["Join Us"](https://dossgollin-lab.github.io/join-the-lab) page.
When projects allow for a broader scope, or more general funding is available, that same page will note how many students the group is looking to take on.
*If you have external funding or a specific research idea, you should reach out (see below) even if there's not a position posted.*

## How to apply

In order to join the group as a graduate student, you must apply to the program of your choice in the [Department of Civil and Environmental Engineering](https://cee.rice.edu/academics/graduate-programs/phd-program).
See [Rice graduate admission guidelines](https://graduate.rice.edu/admissions/how-to-apply).
It is **your responsibility** to keep track of all required deadlines, materials, etc!

### Before formally applying

Applying to graduate school is a time- and money-consuming process.
You are strongly encouraged (though *not required*) to reach out before formally applying as this can help to give both of us a sense of whether it's worth the investment of your time to apply.

**To reach out, please read the instructions below and then fill out [this form](https://forms.gle/MfcpHnA6E3R2NuSn6).**
If you send me an email, you will get a template email directing you to fill out the form.
I get too many emails from prospective students to keep track of all of them effectively.

1. **Decide if you are interested**
    - Read relevant websites and [our papers](https://dossgollin-lab.github.io/publications/) to judge whether this is a good fit.
    - Note the kind of quantitative  research we do, the approaches we use, and the problems we analyze.
    - Feel free to explore websites of coauthors and close collaborators.
    - Review the core values we adopt in the lab group (described int his document) and decide whether they are compatible with your values and goals.
2. **Fill out the form"**
    If you are still interested and see the potential for a good fit, [**fill out the form for prospective applicants**](https://forms.gle/MfcpHnA6E3R2NuSn6).
    - This form asks for a statement of purpose.
    See ["how to write a good application"](#how-to-write-a-good-application) for some helpful tips on how to write a good one!
    Statements that do not follow these tips are unlikely to stand out and will probably not lead to you being accepted.
    -  Fill out all requested questions thoughtfully. I suggest to draft text inputs in another application so that if your internet connection is disrupted nothing is lost.
    -  I will follow up via email.
3. **Video chats**
    - These are intended to evaluate your verbal communications skills and how well you can articulate your interests. If a video chat does not work for you, we can find alternatives.
    - There is no need for fancy backgrounds, formal presentations, or for dressing up.
    - If this is of joint interest, you should apply formally to the department (see next)

### The formal application

Whether you have been in touch or not, **you must apply to the [Department of Civil and Environmental Engineering at Rice](https://cee.rice.edu/)**.
This will give the department an opportunity to view your transcripts, letters of recommendation, and statement of purpose.
Of these, the step you most control is the statement of purpose; see [below](#how-to-write-a-good-application) for tips on information on how to write a strong statement of purpose that enhances your chances of admission.

After formal applications are submitted, I will follow up with information on a formal interview.

## How to write a good application

Although your application is assessed holistically, you should focus on crafting the **statement of purpose** to make sure that it clearly and obviously answers all three of these questions.
A good statement of purpose should clearly articulate:

1. How would joining this lab group advance your career and life goals?
1. What kind of research would you like to carry out in your Ph.D.?
1. How does your current skill-set map to the needs for the project? What will you need to learn?
1. Why is James the right supervisor for you to carry out this research?
1. What synergies do you see with the group?

If your statement of purpose does not directly address these questions, it is unlikely to stand out and will decrease your chances of being accepted.
For some additional generic advice, check out the following resources:

1. Matt Might's [How to Get Into Grad School](http://matt.might.net/articles/how-to-apply-and-get-in-to-graduate-school-in-science-mathematics-engineering-or-computer-science/) post (note that this is aimed at computer science, but is overall similar)
1. [this MIT guide](https://mitcommlab.mit.edu/cheme/commkit/graduate-school-personal-statement/) to the statement of purpose
1. [Rice University's guidance](https://graduate.rice.edu/news/grad-school-101-writing-personal-statement) to the statement of purpose
1. Chris Blattman's [Twitter Thread](https://threadreaderapp.com/thread/1593606505340801024.html) and [blog post](https://chrisblattman.com/blog/2022/01/11/phd-applicants-writing-your-statement-of-purpose/) on writing a strong statement of purpose (tailored to economics and social sciences, but  the advice is highly applicable!)

## FAQ

**Are positions fully funded?**

In short: yes.
All Ph.D. positions within the group will be fully funded.
That includes tuition support, a stipend, and other benefits -- see Rice's [2022 Announcement](https://graduate.rice.edu/news/current-news/rice-raises-its-minimum-phd-stipend-32000-increases-adams-moseley-loan).
You will get more details in your formal offer letter if accepted.

**Should I write a research proposal?**

You should include some research goals and ideas in your statement of purpose, but don't write a separate research proposal.
See the advice listed above for more details.

**How is it the best way to find a master/Phd opportunity?**

When you're applying to an undergraduate program, you care the most about the university.
When applying to a PhD (in engineering at least), you care the most about the research group you will be working with.

Start by thinking about what kind of research you want to do.
Do you like lab work or computational work?
What problems do you want to use?
What classes do you want to take?
Sketch out some research ideas that interest you.
Then, conduct a literature review and find out who is working in this space.
Look at their web pages and papers and look for research groups that appeal to you.

**How often do students usually travel for conferences?**

After the first year (primarily classes) I aim to fund students to go to the American Geophysical Union Fall Meeting (1 week in December) or the American Society of Civil Engineers Environment / Water Resources Institute annual meeting (1 week in May).
There are also lots of smaller and more targeted workshops that are often great experiences -- they often have some student travel grants and with planning we can often fund student travel.

**What are things you wish more students knew before joining your program?**

*I got some feedback from current students for this.*

1. Balancing course requirements (roughly 6 courses -- see student handbook for details) and research can be a challenge, especially for first-year graduate students who generally have the heaviest courseloads.
1. For anyone doing modeling or data-driven work, most of your day will be spent (i) reading, (ii) writing, or (iii) coding. You should strive to improve your effectiveness in all three areas and plan to spend much of your day at a computer (which also means being deliberate about getting out of your computer!)
1. You will get more out of grad school (this applies to any program!) if you have a clear idea of what you want to learn and what you want to get out of grad school.

**What is the worst quality of life pain point that your students go through?**

*I got some feedback from current students for this.*

1. Trying to learn how to do research while also taking a heavy courseload can make for a tough first semester (this was also my experience).

**How has the lab planned and handled for student's growth throughout their graduate program?**

*I got some feedback from current students for this.*
We're still figuring this out and will continue to adapt as we learn more.
Students learn best from each other, so we have regular reading groups, where we meet (often with friends from other groups) to discuss papers.
We help each other prepare for conferences, give each other feedback on papers, etc.
This only works in an environment where we trust each other (both giving and getting feedback require trust) so we need to hold ourselves and each other to a high standard of integrity (i.e., be trustworthy!)
As a young / small group, it's also important to have interaction with people outside the group -- we have meetings and social events with other lab groups, and most students are working on collaborative projects that include people from beyond our group.

**How are publication credits discussed in the lab?**

Please see [authorship guidelines](../posts/authorship.qmd).
Journals typically have clear expectations about what constitutes authorship and we follow those guidelines.
The most important rule is to have clear conversations about authorship early on (this is the PI's responsibility but students are always welcome to ask about authorship!)

**How has the lab dealt with academic and social misconduct situations (plagiarism, bullying, harassment, misogyny, racism, transphobia, etc)?**

So far we've been fortunate to have avoided significant academic and social misconduct.
We obviously follow Rice University policies.
We've also developed a [policy on harassment](../expectations/harassment.qmd) and other expectations that will guide us if (when) these come up.
In general we set high expectations for ourselves and for one another because a collaborative and open environment, which benefits everyone, requires mutual trust and respect.
